"""
supabase/migrations/ 의 .sql 전부를 대시보드에 한 번에 붙여넣을 파일 하나로 합친다.
파일 목록은 글롭으로 읽으므로 마이그레이션을 추가할 때 이 스크립트는 손대지 않는다.

    py scripts/build_apply_all.py

산출: supabase/APPLY_ALL.generated.sql (gitignore 대상 — 원본은 migrations/)

왜 PowerShell 한 줄이 아니라 스크립트인가:

  Get-ChildItem ... | ForEach-Object { Get-Content $_.FullName -Raw } |
    Set-Content out.sql -Encoding utf8

이 형태가 한글을 깨뜨린다. Windows PowerShell 5.1의 `Get-Content`는 BOM 없는
UTF-8 파일을 시스템 기본 인코딩(한국어 Windows에서는 CP949)으로 읽는다.
그래서 읽는 순간 이미 깨지고, 그걸 -Encoding utf8 로 쓰면 깨진 상태가 그대로
굳는다. 대시보드에서는 다음처럼 터진다:

    ERROR: 42601: syntax error at or near "?"
    LINE 571: raise exception '?꾩뭅?곕? ?대쫫???낅젰??二쇱꽭??;

파이썬은 encoding='utf-8' 을 명시할 수 있어 이 함정이 없다.
출력도 BOM 없이 쓴다 — Supabase SQL 에디터가 선두 BOM을 토큰으로 읽는 일이 있다.
"""

from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "supabase", "migrations")
OUT = os.path.join(ROOT, "supabase", "APPLY_ALL.generated.sql")

HEADER = """\
-- Generated from supabase/migrations/. Do not edit this file.
-- Apply: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run
-- Regenerate: py scripts/build_apply_all.py
"""


def main() -> int:
    files = sorted(f for f in os.listdir(SRC_DIR) if f.endswith(".sql"))
    if not files:
        print(f"no .sql files in {SRC_DIR}", file=sys.stderr)
        return 1

    parts = [HEADER]
    for name in files:
        with open(os.path.join(SRC_DIR, name), encoding="utf-8") as fh:
            body = fh.read()
        parts.append(f"\n-- {'>' * 20} {name} {'>' * 20}\n\n{body}")

    text = "\n".join(parts)
    # newline='\n' 로 고정: 대시보드에 붙여넣을 텍스트라 CRLF가 섞일 이유가 없다.
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)

    # 합치는 과정에서 한글이 상했는지 즉시 확인한다. 깨진 파일을 조용히
    # 내보내면 대시보드에서야 발견되고, 그때는 원인이 한참 멀어져 있다.
    korean = sum(1 for ch in text if "가" <= ch <= "힣")
    if korean == 0:
        print("ERROR: no Hangul found - the merge likely corrupted encoding", file=sys.stderr)
        return 1

    print(f"written: supabase/APPLY_ALL.generated.sql")
    print(f"  merged : {', '.join(files)}")
    print(f"  size   : {len(text):,} chars / {text.count(chr(10)) + 1} lines")
    print(f"  hangul : {korean:,} chars (ok)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
